"""upgrade the login model

Revision ID: 3e4047e83790
Revises: 5241dd7a1b66
Create Date: 2026-05-12 15:48:05.631623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4047e83790'
down_revision: Union[str, Sequence[str], None] = '5241dd7a1b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logins', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logins', 'title')
    # ### end Alembic commands ###
