"""denormalización en la tabla logins para aumentar el rendimiento

Revision ID: 5241dd7a1b66
Revises: e826384b8b40
Create Date: 2026-01-07 19:13:59.104940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5241dd7a1b66'
down_revision: Union[str, Sequence[str], None] = 'e826384b8b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logins', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'logins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logins', type_='foreignkey')
    op.drop_column('logins', 'user_id')
    # ### end Alembic commands ###
